services:
  miniflux:
    image: miniflux/miniflux:2.0.41
    ports:
      - 11500:8080
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - miniflux/config.env

  kanboard:
    image: kanboard/kanboard:v1.2.17
    ports:
      - 12000:80
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - kanboard/config.env

  database:
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database/config.env
    healthcheck:
      test: ["CMD", "/utils/healthcheck.sh"]
      interval: 10s
      start_period: 50s
      retries: 3
