services:
  miniflux:
    image: miniflux/miniflux:2.0.41
    ports:
      - 11500:8080
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - miniflux/config.env

  kanboard:
    image: kanboard/kanboard:v1.2.17
    ports:
      - 12000:80
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - kanboard/config.env
    volumes:
      - kanboard_data:/var/www/app/data

  linkding:
    image: sissbruecker/linkding:1.17.2
    ports:
      - 11700:9090
    env_file:
      linkding/config.env
    volumes:
      - linkding_data:/etc/linkding/data

  database:
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database/config.env
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "/utils/healthcheck.sh"]
      interval: 10s
      start_period: 50s
      retries: 3

volumes:
  database_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/database

  kanboard_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/kanboard

  linkding_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/linkding
